name: gymlog
description: "GymLog - Track your workouts, monitor progress, and crush your goals."

version: 1.2.5+39

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  sqflite: ^2.4.1
  path: ^1.9.1
  shared_preferences: ^2.3.5
  image_picker: ^1.1.2
  path_provider: ^2.1.5
  gal: ^2.3.0
  google_fonts: ^8.1.0
  intl: ^0.20.2
  flutter_svg: ^2.0.10+1
  geolocator: ^14.0.0
  flutter_map: ^8.1.1
  latlong2: ^0.9.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.14.3
  flutter_native_splash: ^2.4.6

flutter_launcher_icons:
  android: true
  ios: false
  image_path: "assets/images/app_icon.png"
  adaptive_icon_background: "#000000"
  adaptive_icon_foreground: "assets/images/app_icon.png"
  min_sdk_android: 21

flutter_native_splash:
  color: "#000000"
  image: assets/images/splash_logo.png
  android_12:
    image: assets/images/app_icon.png
    color: "#000000"
    icon_background_color: "#000000"

flutter:

  uses-material-design: true

  assets:
    - assets/images/musclemap.png
    - assets/images/muscle_map.png
    - assets/images/splash_logo.png
    - assets/images/app_icon.png

